template = "https://github.com/giellalt/template-lang-und"
rev_id = 293
template_sha = "d22e247baeffac26e2fcc89a2b69592e66f6d04d"

[replacements]
__GLOTTOLOG_ID__ = "puru1264"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-pur"
__UND2C__ = "pur"
__UNDEFINED__ = "Purubora"
__UND__ = "pur"
