template = "https://github.com/giellalt/template-lang-und"
rev_id = 322
template_sha = "eb14866dc080346b46def6f27a66b1b5eca59898"

[replacements]
__GLOTTOLOG_ID__ = "puru1264"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-pur"
__UND2C__ = "pur"
__UNDEFINED__ = "Purubora"
__UND__ = "pur"
